### ISSUE TITLE
No Build output

### ISSUE THREAD

**Issue by pehrlich** [macoscope/CodePilot#16]
New to C++ here.  Just cloned the repo, installed the PackageMaker app, and built the project.  But there's no `.xcplugin` in `build/Release` - There's actually no `build` folder at all.   

What could be happening?

Thanks

**Comment by justMaku** [comment]
Hi,

I've checked and we have changed our setup a little and building the project automatically installs the plugin bundle at:
```
~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/
```
