### ISSUE TITLE
Can't open CodePilot

### ISSUE THREAD

**Issue by onmyway133** [macoscope/CodePilot#17]
I build the CodePilot project and see the the CodePilot3.xcplugin in the Xcode/Plug-in folders. Then I restart Xcode 5, hit CMD-SHIFT-X as guided, but nothing happens

**Comment by bartekchlebek** [comment]
Current master tested with Xcode 5 seems to work fine. If you can reproduce this problem @onmyway133 please feel free to reopen this issue. Thanks! 👍
