### ISSUE TITLE
xcode6.3 not work

### ISSUE THREAD

**Issue by hahafk** [macoscope/CodePilot#34]
press CMD + SHIFT + X,nothing happens.

**Comment by hahafk** [comment]
just add DVTPlugInCompatibilityUUIDs at info.plist can resolve this question.
defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID

**Comment by wangyhzzz** [comment]
@hahafk thank you for mention that .
 after add  9F75337B-21B4-4ADC-B558-F9CADF7073A7 to the DVTPlugInCompatibilityUUID, CodePilot work again for me.

**Comment by everbelieve** [comment]
still can't work for me

**Comment by everbelieve** [comment]
@wangyhzzz  DVTPlugInCompatibilityUUID --> 9F75337B-21B4-4ADC-B558-F9CADF7073A7 has already save into info.plist, but still not work

@hahafk after adding DVTPlugInCompatibilityUUIDs, Xcode crashed

**Comment by everbelieve** [comment]
solved! 
add 9F75337B-21B4-4ADC-B558-F9CADF7073A7 into DVTPlugInCompatibilityUUIDs in file
~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CodePilot3.xcplugin/Contents/info.plist
(can get 9F7533... in info.plist in Xcode.app/Content)

**Comment by justMaku** [comment]
That has been already fixed, thanks for the feedback.
