### ISSUE TITLE
CodePilot Can't Work in Version 6.3.2 (6D2105) Of XCode

### ISSUE THREAD

**Issue by chanboo1985** [macoscope/CodePilot#42]
if inscribe。
before can use。
but ，after the upgrade xcode and osx，codepilot can't work.
please resolve this issues,thanks!

**Comment by bartekchlebek** [comment]
Please have a look at #40 and let us know if it appears to be the same problem you have. Thanks!

**Comment by chanboo1985** [comment]
yes,it appears to be the same problem. Has had the similar pop-up message before, but not today, use shortcuts CMD + shift + x without any hints

**Comment by bartekchlebek** [comment]
Duplicate of #40
