### ISSUE TITLE
Difference between CodePilot and the similar system view?

### ISSUE THREAD

**Issue by gerchicov-bp** [macoscope/CodePilot#44]
I mean Cmd+Shift+O.
Could you explain the advantages of your product (maybe even in readme)? Because I saw one disadvantage only - your product is much slower.

**Comment by goktugyil** [comment]
I was wondering the same thing

**Comment by justMaku** [comment]
CodePilot was created in the ancient times of Xcode 3 where there was no built-in functionality like this. After Apple added such tool with XCode 4 we decided to opensource our solution for learning purposes. I hope this answers your question.
