### ISSUE TITLE
Not work in Xcode 6.3.1

### ISSUE THREAD

**Issue by XUJiahua** [macoscope/CodePilot#45]
Hello,
I need help.
I installed CodePilot via Alcatraz. But type cmd + shift + x, nothing happen. I tried to restart Xcode. 
I read this thread. https://github.com/macoscope/CodePilot/issues/34
And checked in my computer, 9F75337B-21B4-4ADC-B558-F9CADF7073A7 has already saved into both info.plist.

**Comment by bartekchlebek** [comment]
Try removing the plugin and installing it anew. There was a bug that caused the plugin not be loaded properly, maybe you don't have the newest version and it's that.

If that doesn't help, please take a look into `Console.app` after launching Xcode if there are any logs that might help us.

**Comment by XUJiahua** [comment]
Thanks man! I checked the logs from Console.app and added the missing UUID to DVTPlugInCompatibilityUUIDs in ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CodePilot3.xcplugin/Info.plist.
