### ISSUE TITLE
Xcode 6.4 doesn't load the plugin

### ISSUE THREAD

**Issue by mindz-eye** [macoscope/CodePilot#47]
Xcode gives a warning on launch about 3rd party bundles and asks if it should load them. No matter what, CodePilot doesn't work after that. 
Notes:
- DVTPlugInCompatibilityUUID was updated to the actual value
- Alcatraz and other plugins work after performing steps described in https://github.com/supermarin/Alcatraz/issues/307

**Comment by tylerjvick** [comment]
Having the same issue

**Comment by ainame** [comment]
I have same one...

**Comment by bartekchlebek** [comment]
Have you tried reinstalling the plugin? Are you sure you're running the newest version? If so, could you look into logs and see if there's anything helpful there becaus it runs ok with Xcode 6.4 on my end.

**Comment by mindz-eye** [comment]
Yep, reinstalling the plugin helps. Thanks
