### ISSUE TITLE
Not working in Xcode 7.1

### ISSUE THREAD

**Issue by alem0lars** [macoscope/CodePilot#57]
I've installed the plugin using Alcatraz.

However pressing CMD+SHIFT+X, code pilot doesn't pop up

**Comment by ski081** [comment]
I am seeing the same thing. I have tried uninstalling/reinstalling both manually and using Alcatraz. Also opened up info.plist to ensure the compatibility UUID was in there for 7.1. CodePilot team, I am willing to help debug, but have never done plugin development. Is there any documentation on how to get started?

**Comment by Zcgong** [comment]
I have the same thing.

**Comment by DominicFrei** [comment]
+1 for Xcode 7.1.1

**Comment by dabing1022** [comment]
It seems conflict to XVim shortcuts (CMD + SHIFT + X). How can I change the keybinding? 

`Xcode`-->`Preferences`-->`Key Bindings`, I can't find it.

Thanks. :+1:

**Comment by masterkk** [comment]
+1 for Xcode Version 7.1 (7B91b)

**Comment by ooopscc** [comment]
@dabing1022 If you build the XVim yourself, you will find the shortcut in key bindings. The alcatraz seems not generates the shortcut properly for XVim in key bindings.

**Comment by dabing1022** [comment]
@ooopscc Yes, I changed the shortcut by building XVIM through Xcode instead of Alcatraz. :100:

**Comment by andycoder7** [comment]
@dabing1022 But codepilot is still not working...

**Comment by lizhuang** [comment]
+1 for Xcode 7.1.1

**Comment by mingyue1991** [comment]
+1 for xcode7.2

**Comment by micnguyen** [comment]
+1 for 7.2

**Comment by bartekchlebek** [comment]
Xcode 7.2 should be supported as soon as #60 is merged.
Do 7.1 and 7.1.1 still cause problems?

**Comment by devxin** [comment]
+1 for 7.3

**Comment by rafsouzap** [comment]
Hi guys... I couldn't make it work in my Xcode 7.2.1. All tips found here not solved this problem.
I uninstalled another plugin (XAlign) that used the same key binding, but not solved too.

**Comment by bubski** [comment]
Should be fixed with #60
